/**
 * facts-core.mjs  ::  the ONE derivation of every live number the site states.
 *
 * WHY THIS FILE EXISTS
 * On 2026-07-25 an audit found "$5,000 to $15,000" stated on 15 pages, including the
 * AutoDealer priceRange JSON-LD that Google reads and the answer text of several
 * FAQPage blocks, against a real live band of $8,995 to $15,995. A stated price range
 * that no vehicle in stock falls inside is a violation of 14 Ill. Adm. Code 475.390.
 * The root cause was not carelessness: the band was hardcoded in prose in 19 files and
 * in compliance-guardrails.md itself, so every copy was correct on the day it was
 * written and wrong a few sales later.
 *
 * The rule that follows from that: NO NUMBER LIVES IN A PAGE. Price band, unit count,
 * review count, rating and the service city list are derived here, once, and every
 * consumer reads the generated output. A hardcoded ledger value anywhere else is a
 * lint failure.
 *
 * Consumers of the generated site/src/data/facts.json:
 *   - Astro pages and components (import the JSON directly)
 *   - scripts/build-facts.mjs (writes it; runs as site prebuild and from build-inventory)
 *   - web_assets/llms.txt generation
 *   - operations/build_ai_knowledge_base.py (the GoHighLevel assistant's fact sheet)
 *   - scripts/lint-copy.mjs (asserts no page states these numbers independently)
 *
 * This module is pure: it takes parsed JSON in and returns a plain object. It reads no
 * files and writes none, so it is trivially testable and cannot fail a build on IO.
 */

const US = new Intl.NumberFormat('en-US');

/** Money with no cents, the only price format the site uses. */
function usd(n) {
  return `$${US.format(Math.round(n))}`;
}

/**
 * Derive every live fact.
 *
 * @param {object}   input
 * @param {Array}    input.vehicles  parsed vehicles.json (all records, sold included)
 * @param {object}   input.reviews   parsed reviews_meta.json  { rating, count, updated }
 * @param {Array}    input.suburbs   parsed suburbs.json (for the service city list)
 * @param {string}  [input.now]      ISO timestamp, injectable so builds are reproducible
 * @returns {object} the facts ledger
 */
export function deriveFacts({ vehicles = [], reviews = {}, suburbs = [], now = null } = {}) {
  // A car is for sale when it is not sold. build-inventory.js already guarantees the
  // active set equals the newest DealerCenter feed, so this needs no other filter.
  const live = vehicles.filter(v => v && v.status !== 'sold');
  const prices = live
    .map(v => Number(v.price))
    .filter(p => Number.isFinite(p) && p > 0)
    .sort((a, b) => a - b);

  const unitCount = live.length;
  const priced = prices.length;

  // Degrade honestly rather than throwing. A thrown error here would fail the Astro
  // build, and on Vercel a failed build keeps the PREVIOUS deployment serving, which
  // means yesterday's inventory at yesterday's prices. Advertising a sold car is a
  // worse outcome than omitting a price range for one build, so this never throws.
  const usable = priced > 0;

  const priceMin = usable ? prices[0] : null;
  const priceMax = usable ? prices[priced - 1] : null;

  const carWord = unitCount === 1 ? 'car' : 'cars';
  const carWordEs = unitCount === 1 ? 'auto' : 'autos';

  const cities = suburbs
    .map(s => s && s.city)
    .filter(Boolean);

  return {
    // Provenance, so a human opening the file knows not to edit it.
    generated: now || new Date().toISOString(),
    source:
      'GENERATED by scripts/build-facts.mjs from vehicles.json, reviews_meta.json and ' +
      'suburbs.json. Never hand edit. See scripts/facts-core.mjs for why.',

    inventory: {
      usable,
      unitCount,
      pricedCount: priced,
      priceMin,
      priceMax,

      // Preformatted strings, so no consumer reimplements currency formatting and
      // drifts on the comma or the cents.
      priceMinText: usable ? usd(priceMin) : null,
      priceMaxText: usable ? usd(priceMax) : null,

      // The band. Written "to", never with a dash, because a hyphen or en dash between
      // two prices is both a house style violation and harder to read aloud, which
      // matters for the answer engines that now quote this text.
      bandText: usable ? `${usd(priceMin)} to ${usd(priceMax)}` : null,
      bandTextEs: usable ? `de ${usd(priceMin)} a ${usd(priceMax)}` : null,

      // The single safest phrasing: an open ended floor cannot go stale upward the way
      // a ceiling can, so this is the default for prose that does not need the full band.
      fromText: usable
        ? `Inventory currently priced from ${usd(priceMin)}`
        : 'Inventory pricing is listed on each vehicle',
      fromTextEs: usable
        ? `Inventario disponible desde ${usd(priceMin)}`
        : 'El precio de cada vehiculo aparece en su pagina',

      stockText: `${unitCount} ${carWord} in stock today`,
      stockTextEs: `${unitCount} ${carWordEs} disponibles hoy`,

      // For the AutoDealer priceRange property. Schema.org takes a free text range;
      // Google reads it, so it must match what the pages say.
      priceRange: usable ? `${usd(priceMin)} to ${usd(priceMax)}` : null,
      priceRangeEs: usable ? `${usd(priceMin)} a ${usd(priceMax)}` : null,
    },

    reviews: {
      // Never hardcoded anywhere else. reviews_meta.json is refreshed from a live
      // Google read inside the daily GBP routine; the scraper that used to write it
      // went blind and was disabled, so this is the only sanctioned path.
      rating: reviews.rating ?? null,
      count: reviews.count ?? null,
      updated: reviews.updated ?? null,

      // Always one decimal. JSON 5.0 parses to the JS number 5, so naive
      // interpolation yields "Rated 5 on Google" while every existing surface and the
      // approved canonical string say "5.0". toFixed(1) also renders 4.8 correctly.
      ratingValue: reviews.rating != null ? Number(reviews.rating).toFixed(1) : null,

      // "Rated 5.0 on Google" style. A count is deliberately NOT baked into a phrase:
      // review counts move weekly and a stale count is the drift that started this.
      ratingText: reviews.rating != null ? `Rated ${Number(reviews.rating).toFixed(1)} on Google` : null,
      ratingTextEs: reviews.rating != null ? `Calificacion de ${Number(reviews.rating).toFixed(1)} en Google` : null,
    },

    cities,
    citiesText: cities.length ? cities.join(', ') : null,
  };
}

/**
 * Placeholder resolution for prose that lives inside JSON (suburbs.json, faq.json).
 * Those files are hand authored narrative, so the numbers inside them are written as
 * {{tokens}} and substituted at build time. Unknown tokens are left untouched on
 * purpose: silently deleting one would quietly change the meaning of a sentence, and
 * lint-copy.mjs fails the check when an unresolved token reaches built output.
 *
 * @param {string} text
 * @param {object} facts  output of deriveFacts
 */
export function resolveTokens(text, facts) {
  if (typeof text !== 'string' || !text.includes('{{')) return text;

  const table = {
    'price.band': facts.inventory.bandText,
    'price.bandEs': facts.inventory.bandTextEs,
    'price.min': facts.inventory.priceMinText,
    'price.max': facts.inventory.priceMaxText,
    'price.from': facts.inventory.fromText,
    'price.fromEs': facts.inventory.fromTextEs,
    'inventory.count': facts.inventory.unitCount == null ? null : String(facts.inventory.unitCount),
    'inventory.stock': facts.inventory.stockText,
    'inventory.stockEs': facts.inventory.stockTextEs,
    'reviews.rating': facts.reviews.ratingValue,
    'reviews.count': facts.reviews.count == null ? null : String(facts.reviews.count),
    'reviews.ratingText': facts.reviews.ratingText,
    'cities': facts.citiesText,
  };

  return text.replace(/\{\{\s*([a-zA-Z.]+)\s*\}\}/g, (whole, key) => {
    const val = table[key];
    return val == null ? whole : val;
  });
}

/** Every token name resolveTokens understands, for the linter's error messages. */
export const KNOWN_TOKENS = [
  'price.band', 'price.bandEs', 'price.min', 'price.max', 'price.from', 'price.fromEs',
  'inventory.count', 'inventory.stock', 'inventory.stockEs',
  'reviews.rating', 'reviews.count', 'reviews.ratingText', 'cities',
];
